"""Write docs/cli.md from the command's own parsers, so the reference cannot
drift from the code.

    python -m neuroatlas.cli._gendocs            # rewrite docs/cli.md
    python -m neuroatlas.cli._gendocs --check    # exit 1 if it is stale
"""
from __future__ import annotations

import argparse
import io
import os
import sys
from contextlib import redirect_stdout
from pathlib import Path
from typing import List

from neuroatlas import _paths

HEADER = """# `neuroatlas` command reference

Generated by `python -m neuroatlas.cli._gendocs` from the command's own
parsers; do not edit by hand. The user guide is [user_guide.md](user_guide.md).

Global options, before or after the command:

```
{usage}
```

"""


def _help_of(parser: argparse.ArgumentParser) -> str:
    os.environ["COLUMNS"] = "88"
    return parser.format_help().rstrip()


def _parsers():
    """(title, parser) for every command and sub-action, in COMMANDS order."""
    from neuroatlas.cli import COMMANDS, command_parser

    for name, cmd in COMMANDS.items():
        parser = command_parser(name)
        yield name, cmd.summary, parser
        for action in parser._actions:
            if isinstance(action, argparse._SubParsersAction):
                for sub_name, sub in action.choices.items():
                    if sub.add_help:
                        yield f"{name} {sub_name}", None, sub


def render() -> str:
    from neuroatlas.cli import USAGE, global_options_text

    out = [HEADER.format(usage=USAGE + "\n\n" + global_options_text())]
    out.append("## Commands\n")
    rows = []
    for title, summary, _ in _parsers():
        if summary:
            rows.append(f"| [`{title}`](#{title.replace(' ', '-')}) | {summary} |")
    out.append("| command | what it does |\n|---|---|\n" + "\n".join(rows) + "\n")
    for title, summary, parser in _parsers():
        level = "##" if " " not in title else "###"
        out.append(f"\n{level} {title}\n")
        if summary:
            out.append(f"{summary}\n")
        out.append(f"```\n{_help_of(parser)}\n```\n")
    return "\n".join(out)


def target() -> Path:
    root = _paths.checkout_root()
    if root is None:
        raise SystemExit("error: run this from a source checkout")
    return root / "docs" / "cli.md"


def main(argv: List[str] | None = None) -> None:
    args = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    args.add_argument("--check", action="store_true")
    opts = args.parse_args(argv)
    text = render()
    path = target()
    if opts.check:
        if not path.is_file() or path.read_text() != text:
            print(f"{path} is stale: run `python -m neuroatlas.cli._gendocs`", file=sys.stderr)
            raise SystemExit(1)
        print(f"{path} is current")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
